services:

#-------------- database instance-------------------
  #postgreslq
  postgresql-db:
    image: postgres:latest
    container_name: postgresql-db
    ports:
      - "5432:5432"
    networks:
      - appli-stack
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data

networks:
  appli-stack:
volumes:
  postgres_db: