apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-persistent-volume
  labels:
    app: db-persistent-volume
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
  labels:
    app: db-persistent-volume-claim
  namespace: bank-account-ns
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M