apiVersion: v1
kind: Service
metadata:
  name: business-microservice-operation
  labels:
    app: business-microservice-operation
  namespace: bank-account-ns
spec:
  selector:
    app: business-microservice-operation
  ports:
    - protocol: TCP
      port: 8104
      targetPort: 8104
  type: NodePort
